# Generated by Django 4.0.6 on 2023-03-04 19:44

import apps.photos.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=5000)),
                ('slug', models.SlugField(help_text='Enter a unique, descriptive URL path (e.g. based on the name) containing only lowercase letters, numbers,  and hyphens (instead of spaces). ', unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid'), apps.photos.models.validate_lowercase])),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 't_collection',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 't_country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_image', imagekit.models.fields.ProcessedImageField(help_text='Upload images with a width of 2000px or greater to avoid low visual quality (e.g. pixelation) on larger screen sizes.', upload_to='', verbose_name='image file')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Enter a unique, descriptive URL path (e.g. based on the title) containing only lowercase letters, numbers,  and hyphens (instead of spaces). ', max_length=60, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid'), apps.photos.models.validate_lowercase])),
                ('description', models.TextField(max_length=5000)),
                ('location', models.CharField(help_text='Enter the specific location where the photo was taken.', max_length=255)),
                ('date_taken', models.DateField()),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('collections', models.ManyToManyField(blank=True, to='photos.collection')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.country')),
            ],
            options={
                'db_table': 't_photo',
            },
        ),
    ]
